spring:
  datasource:
    url: jdbc:mysql://192.168.11.114:3306/test?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: Sear123


server:
  port: 7172

#JWT 秘钥
jwt:
  secret: webdemo
  expiredTime: 3600 #单位‘秒’
